---
# handlers file for ubuntu-check
- name: restart bind9
  service: name=bind9 state=restarted

- name: reload systemd
  command: systemctl daemon-reload

- name: reload journald
  command: systemctl restart systemd-journald