---

#csirtg_provider: "{{ ansible_hostname }}"
csirtg_provider: "{{ ansible_fqdn }}"
csirtg_tags: 'scanner,ssh'
docker_container_name: 'ssh-auth-logger'

# user and group
app_user: prism
app_group: "{{ app_user }}"
app_user_home: "/home/{{ app_user }}"

# interface created by tinc/avahi, don't change!
zsys_interface: "zyre:avahi"

# cif, probably don't need to change
smrt_provider: localhost
smrt_version: 0.0.0a40
indicator_version: 0.0.0b14
smrt_client: zyre

# zyre channel on which gateway joins
zyre_group: ssh

