---
- name: run yum install epel-release
  package: name=epel-release state=present
  when: (ansible_distribution == "CentOS")

- name: Add apt HTTPS support
  package: name=apt-transport-https state=present
  when: (ansible_distribution == "Ubuntu")

- name: Add HTTPS support
  package: name=ca-certificates state=present

## see https://github.com/wesyoung/pyzyre/wiki
#- name: Add apt zeromq keys
#  apt_key: url='http://download.opensuse.org/repositories/home:wesyoung:zeromq/xUbuntu_16.04/Release.key'
#  when: (ansible_distribution == "Ubuntu")
#
#- name: Add apt zeromq repo
#  apt_repository: repo='deb http://download.opensuse.org/repositories/home:/wesyoung:/zeromq/xUbuntu_16.04/ /'
#  when: (ansible_distribution == "Ubuntu")
#
#- name: Add yum zeromq repo
#  yum_repository:
#    name: network_messaging_zeromq_git-draft
#    description: network_messaging_zeromq_git-draft
#    baseurl: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/CentOS_7/
#    gpgkey: http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/CentOS_7//repodata/repomd.xml.key
#    gpgcheck: yes
#  when: (ansible_distribution == "CentOS")
####

- name: Update apt cache if needed.
  apt: update_cache=yes upgrade=yes
  when: (ansible_distribution == "Ubuntu")

#- name: install ubuntu deps
#  package:
#    state: latest
#    pkg: "{{ item }}"
#  with_items:
#    - linux-image-extra-virtual
#    - htop
#    - python-virtualenv
#    - python-pip
#    - virtualenvwrapper
#    - libssl-dev
#    - aptitude
#    - uuid-dev
#    - libzyre-dev
#  when: (ansible_distribution == "Ubuntu")
#
#- name: install centos deps
#  package:
#    state: latest
#    pkg: "{{ item }}"
#  with_items:
#    - htop
#    - python-virtualenv
#    - python-pip
#    - gcc
#    - python-devel
#    - libffi-devel
#    - openssl-devel
#    - htop
#    - git
#    - "@Development Tools"
#    - sqlite-devel
#    - python-virtualenvwrapper
#    - uuid-devel
#    - uuid
#    - libuuid-devel
#    - zyre-devel
#  when: (ansible_distribution == "CentOS")
#
#- name: upgrade pip
#  pip: name=pip extra_args="--upgrade"
#
#- name: upgrade cython
#  pip: name=cython
#
#- name: install local python deps
#  pip: name="{{ item }}" extra_args="--upgrade --no-binary pyzmq"
#  with_items:
#    - pyzyre==0.0.0a13
