# http://docs.ansible.com/ansible/playbooks_environment.html
# environment:
#   http_proxy: http://proxy.example.com:8080
---
- name: configure platform
  hosts: localhost
  gather_facts: False
  become: True

  vars_files:
    - "vars/main.yml"
    - "../global_vars.yml"

  vars:
    - GH_TOKEN: "{{ lookup('env', 'GH_TOKEN') }}"
    - router_store_args: ''
    - router_hunter_threads: "{{ lookup('env', 'CIF_HUNTER_THREADS') }}"
    - router_hunter_advanced: "{{ lookup('env', 'CIF_HUNTER_ADVANCED') }}"
    - router_gatherer_geo_fqdn: "{{ lookup('env', 'CIF_GATHERER_GEO_FQDN') }}"

  pre_tasks:

    - name: configure repos
      raw: rpm -iUvh http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
      ignore_errors: yes

    - name: update yum
      raw: yum -y update

    - name: configure basics
      raw: yum install -y gcc python-pip python-devel git libffi-devel openssl-devel

    - setup:
       filter: ansible_*

    - name: set store fact
      set_fact:
        router_store_store: 'elasticsearch'
        router_store_nodes: "{{ CIF_ES }}"
      when: CIF_ES is defined and CIF_ES != ""

    - name: set build_sdist
      set_fact:
        cif_build_sdist: CIF_ANSIBLE_SDIST
      when: CIF_ANSIBLE_SDIST is defined

    - import_tasks: tasks/main.yml

  roles:
    - { role: elastic.elasticsearch,
        es_config: {
          node.data: true,
          node.master: true,
        },
        es_version: "5.6.4",
        es_instance_name: 'cif',
        when: router_store_store is defined and router_store_store == 'elasticsearch'
      }
    - { role: csirtgadgets.cif, tags: role-cif }
    - { role: nginx, tags: role-nginx }