# https://semaphoreci.com/community/tutorials/testing-ansible-roles-on-multiple-operating-systems-with-docker-and-semaphore
---
- name: setup /var/log/journal
  file: path=/var/log/journal owner=root group=systemd-journal mode=0775 state=directory

- name: re-configure systemd
  copy: src=journald.conf dest=/etc/systemd/journald.conf owner=root group=root mode=0744
  notify:
    - reload journald

- name: systemd env file
  template: src=cif.env.j2 dest=/etc/cif.env mode=0660 owner="{{ app_user }}" group="{{ app_user }}" 
  tags: configuration

- name: copy /etc/defaults/cif
  template: src=defaults.j2 dest=/etc/default/cif mode=0660 owner="{{ app_user }}" group="{{ app_user }}"

- name: configure /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf line="cif             soft    nofile            20000"

- name: configure /etc/security/limits.conf
  lineinfile: dest=/etc/security/limits.conf line="cif             hard    nofile            30000"

- name: systemd services
  copy: src={{ item }} dest=/etc/systemd/system owner=root group=root mode=0755
  tags: configuration
  with_items:
    - cif-router.service
    - cif-httpd.service
    - csirtg-smrt.service
  notify:
    - reload systemd

- name: enable services at boot
  service: name={{ item }} enabled=yes
  with_items:
    - cif-router.service
    - cif-httpd.service
    - csirtg-smrt.service
