---
# defaults file for centos71-check
firewall_allowed_tcp_ports:
  - "22"
  - "443"
  - '5000'
firewall_allowed_udp_ports: []
firewall_forwarded_tcp_ports: []
firewall_forwarded_udp_ports: []
firewall_additional_rules: []
firewall_log_dropped_packets: true

python_tmp: '/tmp/tmp_install_python'
python_version: '2.7.10'

app_user: cif
app_group: "{{ app_user }}"
app_user_home: "/home/{{ app_user }}"

cif_runtime_path: '/var/lib/cif'
cif_router_config_path: '/etc/cif/cif-router.yml'
cif_store_store: 'sqlite'
cif_hunter_exclude: 'osint.bambenekconsulting.com:dga'
cif_hunter_threads: 0
cif_gatherer_geo_fqdn: 0
cif_hunter_advanced: 0

csirtg_smrt_runtime_path: "{{ cif_runtime_path }}"
csirtg_smrt_cache_path: "{{ cif_runtime_path }}/smrt"
csirtg_smrt_config_path: '/etc/cif/csirtg-smrt.yml'
csirtg_smrt_rules_path: '/etc/cif/rules'
csirtg_smrt_cif_remote: 'http://localhost:5000'
csirtg_smrt_fireball_size: 500
csirtg_smrt_goback_days: 3


geoip_userid: 999999
geoip_key: "000000000000"
geoip_products: GeoLite2-City GeoLite2-Country

pyversion: 2

nginx_key_file: /etc/nginx/ssl/nginx.key
nginx_cert_file: /etc/nginx/ssl/nginx.crt
nginx_conf_file: /etc/nginx/conf.d/cif.conf
nginx_server_name: localhost
