---
- name: "Check for 64-bit"
  fail: msg="Must be install 64-bit"
  when: ansible_architecture != "x86_64"

- name: "Check for Centos"
  fail: msg="Must be CentOS, {{ is_centos }}"
  when: ansible_distribution != "CentOS" and ansible_distribution != "RedHat"

- name: "Check for version 7"
  fail: msg="Must be version 7, {{ is_centos_version }}"
  when: (ansible_distribution_version < "7" or ansible_distribution_version >= "8")


#- include: firewall.yml
#  tags: firewall

- include: deps.yml
  tags: configuration
